name: Github
on: 
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      version:
        description: Manual Trigger
        required: false
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npx jest